[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.build]
cmds = ['npm install', 'npm run build', 'composer install --no-dev --optimize-autoloader']

[phases.start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
